### ISSUE TITLE
Update unit tests to use CentOS 6.7

### ISSUE THREAD

**Issue by kgeorgak** [rackspace-cookbooks/rackspace_users#10]
We need to do that after https://github.com/rackspace-cookbooks/rackspace_users/pull/9 was merged but we need to wait for a solution to https://github.com/customink/fauxhai/issues/163 first

**Comment by martinb3** [comment]
Fauxhai issue is resolved in https://github.com/customink/fauxhai/pull/164. This issue should be unblocked.

**Comment by kgeorgak** [comment]
Fixed in #18
