### ISSUE TITLE
Default sudo 'runas' is root

### ISSUE THREAD

**Issue by TheSeubert** [rackspace-cookbooks/rackspace_users#5]
We have a number of use cases where applications are deployed under different users and unprivileged users need to be able to execute as the deployment application users. 

```
sudo -u deploy_user bundle exec rake db:migrate
sudo -u deploy_user pm2 restart app1
```

As it stands the default sudo settings force only commands to be ran as root:

https://github.com/rackspace-cookbooks/rackspace_users/blob/master/recipes/default.rb#L55

The default is ALL in the sudo cookbook:

https://github.com/chef-cookbooks/sudo/blob/master/resources/default.rb#L27

At the least this should be configurable.

**Comment by kgeorgak** [comment]
@dude051 : I agree, this was hardcoded to root to cover most of the use cases but it should be configurable and default to the same as the sudo cookbook. I'll work on a PR for that.

**Comment by kgeorgak** [comment]
@dude051 Ok, it's still too early here. Just noticed that you made a PR already. Will review that
